---
title: Last updated on Dec-25-2023
# author: 吕洪港
# affiliation : Department of Psychiatry, Renmin Hospital of Wuhan University, Wuhan 430060,China
# email: honggang.lv@whu.edu.cn
# phone: (+86) 17563519453
# www: https://hugolyu.github.io
# date: "Last Updated `r Sys.Date()`"
#output: html_document
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
    extra_css: "body {font-family: 'Times New Roman', serif;}"
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<font face="Times New Roman">

# [Honggang Lyu (吕洪港)]{style="color: navy"}

Department of Psychiatry, Renmin Hospital of Wuhan University, Wuhan 430060,China ｜ honggang.lv\@whu.edu.cn｜<https://hugolyu.github.io>

#### **Seeking scientific positions in academia or industry, including Assistant Professor, Postdoctoral Researcher, and Research Team Leader.**

## [Educations]{style="color: #990000"}

#### **Ph.D. candidate, Psychiatry and Mental Health**

**Department of Psychiatry, Renmin Hospital of Wuhan University, Wuhan 430060, P.R.China**

**Advisor: Dr. [Zhongchun Liu](https://www.researchgate.net/profile/Zhongchun-Liu-2)**

<p align="right">

*09/2023 - Now*

</p>

#### **M.S., Psychiatry and Mental Health**

**Department of Psychology, Affiliated Hospital of Jining Medical University, Jining 272002, P.R.China**

**Advisor: Dr. [Hao Yu](https://www.researchgate.net/profile/Hao-Yu-28)**

<p align="right">

*06/2023 -- 09/2020*

</p>

#### **M.B. Clinical Medicine**

**First School of Clinical Medicine，Binzhou Medical University, Yantai 264003, P.R.China**

<p align="right">

*06/2020 -- 09/2015*

</p>

## [Skills and Professional Experience]{style="color: #990000"}

-   **Study design**: Full experience in trial designing and managing clinical trials, including case-control trials, cohorts, and randomized controlled trials (RCTs).

-   **Leadership**: Experience in leading and supervising research teams of about 5-20 members.

-   **Data analyses**: Experience in conducting clinical statistical analyses. Also proficient in high-throughput omics analysis, such as microbiome, proteomics, transcriptomics, and lipidomics.

## [Professional Experience]{style="color: #990000"}

#### - Brain Function and Psychosomatic Medicine Institute of Huizhou Mental Health Center (Second People's Hospital of Huizhou), Huizhou, China

-   **Scientific Consultant** (Part-time (2021-Now)).
-   **Director** (Full-time (2017-2021)).
-   Main research contents:
    -   **New ECT strategy:** Improved ECT with similar efficacy but reduced side effects: Hybrid-ECT ([*Rong et al., 2019*]((https://doi.org/10.1186/s12888-019-2320-3))), a pioneering approach combining efficacy of standard ECT with reduced cognitive side effects ([*Li et al., 2021*](https://doi.org/10.1016/j.brs.2021.04.017); [*Zhang et al., 2022*](https://doi.org/10.3389/fpsyt.2022.896018)). And further evolved into i-HECT, currently in progress.
    -   **Schizophrenia and coronary artery calcium (CAC)**: Uncovered increased CAC in schizophrenia patients through COVID-19 chest CT analysis ([*Huang et al., 2021*](https://doi.org/10.1016/j.schres.2021.03.002)). Identified potential risk factors including elevated triglycerides and decreased Triiodothyronine ([*Huang et al., 2023*](https://doi.org/10.1016/j.schres.2023.12.007)).
    -   **Gut microbiome in mood disorders**: Explored gut microbiota in patients with major depressive or bipolar disorder, highlighting distinctive microbiota patterns and links to the gut microbial tryptophan biosynthesis and metabolism pathway (MiTBamp)([*Rong et al., 2019*](https://doi.org/10.1016/j.jpsychires.2019.03.017); *Lai et al., 2021 [a](https://doi.org/10.1017/s0033291719003027) & [b](https://doi.org/10.1016/j.jad.2020.09.010)*).
    -   **Additional research endeavors**: Conducted a meta-analysis of MRI network topology in depression patients. ([*Xu et al., 2021*](https://doi.org/10.1016/j.jad.2021.08.120)).

#### - Shenzhen Mental Health Center (Shenzhen Kangning Hospital), Shenzhen, China

-   **Psychiatrist** (2014 - 2017, residency training program).

## [Publications]{style="color: #990000"}

[(Note: #First author, \*Corresponding author)]{style="color: #666666"}

1.  [[**Lv, H. G.#**]{.underline}]{style="color: #990000"}, Li, J.#, Gao, K., Zeng, L., Xue, R., Liu, X., Zhou, C., Yue, W., Yu, H.\* (2022). **Identification of genetic loci that overlap between schizophrenia and metabolic syndrome.** *Psychiatry Research*, *318*, 114947. [DOI](https://doi.org/10.1016/j.psychres.2022.114947) [PMID](https://pubmed.ncbi.nlm.nih.gov/36399892/)

2.  Chen, G.#, [[**Lv, H. G.#**]{.underline}]{style="color: #990000"}, Zhang, X., Gao, Y., Liu, X., Gu, C., Xue, R., Wang, Q., Chen, M., Zhai, J., Yue, W., Yu, H.\* (2022). **Assessment of the relationships between genetic determinants of thyroid functions and bipolar disorder: A mendelian randomization study.**. *Journal of Affective Disorders*, *298*, 373--380. [DOI](https://doi.org/10.1016/j.jad.2021.10.101) [PMID](https://pubmed.ncbi.nlm.nih.gov/34728293/)

3.  Zeng, L.#, [[**Lv, H. G.#**]{.underline}]{style="color: #990000"}, Li, J., Xue, R., Liu, X., Zhou, C., Yu, H.\* (2022). **Cigarette smoking, coffee consumption, alcohol intake, and clozapine metabolism: A Mendelian randomization study.** *Frontiers in Psychiatry*, *13*, 1002235. [DOI](https://doi.org/10.3389/fpsyt.2022.1002235) [PMID](https://pubmed.ncbi.nlm.nih.gov/36245885/)

4.  Zeng, L.#, [[**Lv, H. G.#**]{.underline}]{style="color: #990000"}, Li, J., Xue, R., Liu, X., Zhou, C., Yu, H.\* (2022). **Causal effects of fatty acids on depression: Mendelian randomization study.** *Frontiers in Nutrition*, *9*, 1010476. [DOI](https://doi.org/10.3389/fnut.2022.1010476) [PMID](https://pubmed.ncbi.nlm.nih.gov/36562041/)

    </font>
